### ISSUE TITLE
Halp

### ISSUE THREAD

**Issue by vesq1337** [iDm0nz/BetterMonaco.NET#3]
System.IO.FileNotFoundException how can i fix this

**Comment by iDm0nz** [comment]
Hello,

Did you put Monaco folder in the app's folder?

**Comment by cookie123456** [comment]
What do you mean? And how did you get my email?

**Comment by op0x59** [comment]
He is asking if you setup Monaco correctly, Also he didn't get your email. Github automatically emails you if someone replied to an issue you posted.
