### ISSUE TITLE
Help pls, only a small question

### ISSUE THREAD

**Issue by SykoticCataclysm** [iDm0nz/BetterMonaco.NET#4]
Hey, does the Monaco background have to be the form, or can I make it so the image is the background of a richTextBox or something? And if so, how do I do that?

**Comment by op0x59** [comment]
Please provide more detail on what you are trying to do, it is possible for you to change the background of the monaco editor but doing so would require an api update with that feature. 
As of right now the only way you can change the background of the monaco editor is editing the js/html files yourself. I might add that in.
