### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by RealApost** [iDm0nz/BetterMonaco.NET#5]
Hello It Didn't launch can u help me im using Visual Studio 2019 and i want to use Monaco as a script box

**Comment by op0x59** [comment]
Can you please provide a better description of the problem you are having a mere, "It Didn't launch" doesn't tell me exactly what is happening. An error message or error code would be nice.

**Comment by RealApost** [comment]
I don't really know why when i rebuild it
It won't launch that the problem I think the problem of cefsharp cause i
can't downloaded for Nuget package its but ill try to fix it. And can i put
the folder on anyplace I want?
