### ISSUE TITLE
k

### ISSUE THREAD

**Issue by RealApost** [iDm0nz/BetterMonaco.NET#6]
Look i did everything i think and this is what i add to my form1()

InitializeComponent();
            Monaco monaco1 = new Monaco();
            monaco1.Dock = DockStyle.Fill;
            this.Controls.Add(fastColoredTextBox1);

            monaco1.Initialize("#################");

when i rebuild and build and i launched it didn't load anything the whole form didn't load i didn't see anything is that a problem or? what im using visual Stuido 2019

![image](https://user-images.githubusercontent.com/47253801/58555231-caab1800-81cd-11e9-952f-92918ebdbd1f.png)

**Comment by RealApost** [comment]
There is no problems or errors i don't know the problem

**Comment by RealApost** [comment]
i even did this
![image](https://user-images.githubusercontent.com/47253801/58555322-00e89780-81ce-11e9-8e0d-bc236e437b28.png)

**Comment by iDm0nz** [comment]
I don't remember my code correctly, but passing an argument in Initialize()
isn't needed. you must do it only to specify monaco path

**Comment by RealApost** [comment]
So is it gonna work if I delete Initialize?

**Comment by iDm0nz** [comment]
Don't pass any argument into Initialize.
