### ISSUE TITLE
:)

### ISSUE THREAD

**Issue by RealApost** [iDm0nz/BetterMonaco.NET#7]
Hello It finally Worked

![image](https://user-images.githubusercontent.com/47253801/58565312-567b6f00-81e3-11e9-8f18-f9bb1d69c607.png)

but how can i use the function that when i type anything show the whole word like when i type
p it shows print and many functions like this

![image](https://user-images.githubusercontent.com/47253801/58565415-84f94a00-81e3-11e9-8f97-89033c18819e.png)

and i wanna know how can i customize monaco font and color

**Comment by op0x59** [comment]
AddIntellisense function will add it, just look at the documentation.
