### ISSUE TITLE
Theme not changing

### ISSUE THREAD

**Issue by recreationx** [iDm0nz/BetterMonaco.NET#9]
I am doing

`Monaco monaco1 = new Monaco(); //Creates the Monaco editor.
            monaco1.Dock = DockStyle.Fill; //The control will take the whole form.
            this.panel2.Controls.Add(monaco1); //Add to the form.
            monaco1.SetTheme(MonacoTheme.Dark);
            monaco1.SetLanguage("lua");
            monaco1.SetText("Test");

            monaco1.Initialize();

`

But the instance still remains the same color and text. Help?

**Comment by iDm0nz** [comment]
you're changing stuff too fast, make sure monaco fully loadef THEN you can
do anything

**Comment by recreationx** [comment]
And how would i be able to do that, for example, using a button?

**Comment by op0x59** [comment]
I'm working on a cool little fix for MonacoNET 2.0. It will no longer use default web browser nor cefsharp. It will be efficient and fast and will also not runny any command unless the page is loaded. There is also a field you can set which will be called when the editor is loaded.
